name: azure-dev

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh # Use PowerShell Core for all scripts (the azd hooks are written in PowerShell)

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to fetch an OIDC token for Azure authentication
      contents: read  # Required to checkout code if needed

    steps:
    - name: Print Azure CLI version
      run: |
        az --version
        
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Generate secret and certificate for app registration
      run: |
        $clientAppId = "df4364d3-7ee2-42f8-ad12-73d5932782d9"
        $keyVaultName = "kvoauthbackendsdcluolm"

        # Create certificate in Key Vault and add to app registration
        az ad app credential reset --id $clientAppId --create-cert --keyvault $keyVaultName --cert "client-certificate" --display-name "Client Certificate" --append --output none --debug

        # Create secret on app registration
        $existingSecret = az ad app credential reset --id $clientAppId --display-name "Client Secret" --query "password" --append --output tsv --debug
